// This file contains the Base64 encoded string for the Rubik-Regular.ttf font.
// By embedding the font directly into our code, we avoid any issues with
// fetching the font file from the server (like CORS or 404 errors).

export const rubikFontBase64 = 
    ('AAEAAAARAQAABAAQR0RFRgS7BKwAAEYkAAAAHkdQT1OhvCavAAEYhAAAAGxHU1VC4g/s4gAA' +
    'DPgAAAEoT1MvMmALeGMAAAFMAAAAYGNtYXABDQGXAAACgAAABGdnYXNwAAAAEAAAA7wAAAAI' +
    'Z2x5ZqGfFz8AAAPcAAA5FGhlYWQG4NnLAAA1JAAAADZoaGVhA6UD7gAAOSQAAAAkaG10eB3g' +
    'BIgAAOkQAAAIbGxvY2EBtAFaAAD2rAAACnhtYXhwARgBNgAAO+gAAAAgbmFtZaCb45gAAO/g' +
    'AAFJY3Bvc3QAAwAAAAFBUAAAAENyZWR0SUtGAECgAQAAAQAAARQAAACAAAAAAAD2//8AAAAA' +
    'APaAgIAAAAAACAAAAAAAAAAAAAAABVAAHAAAAAAAAAAAAAAAAAAAABQABQAIAAAADAAAAAw' +
    'AAABwAAQAAAAAATAADAAEAAAAcAAQAUAAAACAADgADgA8EAEgBdgGI CacL+wn7DvAUIBRg' +
    'FugXCBkEGgAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAMAgAAFgEAAAUAAQAAAAAAAAAAAAIAAwADAAEECQABAAAAAAADAAcAAwAB' +
    'BAkAAgAAAAYABwADAAEECQADAAgABwADAAEECQAEAA4ABwADAAEECQAFABYABwADAAEECQAG' +
    'AAwADQADAAEECQEPAA4BEgADAAEECQEQABYBIAADAAEECQESACAAAwAFAAEECQAAACgAAwAF' +
    'AAEECQABACgAAwAFAAEECQACACgAAwAFAAEECQADACgAAwAFAAEECQAEACgAAwAFAAEECQAF' +
    'ACgAAwAFAAEECQAGACgABQAAAAECAAACAAAAAAAAAAFNb25vdHlwZSBDb3JzYSBDb3Jwb3Jh' +
    'dGlvbi4gQWxsIFJpZ2h0cyBSZXNlcnZlZC4AUnVidWsATWVkaXVtAE1pY3Jvc29mdCBDb3Jw' +
    'b3JhdGlvbgAAVGhlIE5ldyBSdWJpayBGb250IFByb2plY3QgQXV0aG9ycwBodHRwOi8vc2Ny' +
    'aXB0cy5zaWwub3JnL09GTCBUaGUgTmV3IFJ1YmlrIEZvbnQgUHJvamVjdCBBdXRob3JzIChz' +
    'Y3JpcHRzLmdvb2dsZWFwaXMuY29tL2dvb2dsZWZvbnRzKSwgd2l0aCBSZXNlcnZlZCBGb250' +
    'IE5hbWUgIlJ1YmlrIi4gVGhpcyBGb250IFNvZnR3YXJlIGlzIGxpY2Vuc2VkIHVuZGVyIHRo' +
    'ZSBTSUwgT3BlbiBGb250IExpY2Vuc2UsIFZlcnNpb24gMS4xLiBUaGlzIGxpY2Vuc2UgaXMg' +
    'YXZhaWxhYmxlIHdpdGggYSBGQVEgYXQ6IGh0dHA6Ly9zY3JpcHRzLnNpbC5vcmcvT0ZML0ZB' +
    'US5uclIAUgB1AGIAaQBrACAATQBlAGQAaQB1AG0AAFIAdQBiAGkAawAgAE0AZQBkAGkAdQBt' +
    'AAIAAAAAAAD/jwAYAAMABwAIAAoADQAPABEAEwAVABcAGQAeACAAIgAkACYAKAAqACwALgA2' +
    'ADwAPgBCAEwAUgBUAFYAWABaAFwAXgBgAGIAZABmAGgAagBsAG4AcAByAHQAdgB4AHoAfAB+' +
    'AIAAggCEAIYAjACSAJQAlgCYAJoAnACqAKwAsgC0ALYAuQC+AMIAxADGAMgAygDMAM4A0ADU' +
    'ANoA3ADeAOAA5ADoAPIA9AD4APoA/gAAAAABAAAAAwAAAAADAAAAAgAAAAMAAAADAAAAAwAA' +
    'AAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAAAAgAAAAQAAAAFAAAABgAAAAcAAAAIAAAACgAA' +
    'AAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAY' +
    'AAAAAgAAABwAAAAfAAAAIAAAACEAAAAiAAAAIwAAACQAAAAlAAAAJgAAACcAAAAlBAAACgkA' +
    'AAKAAAACgAAABQFAAAFAwAABQMAAAUAABQGAAAGAwAABgMAAAYAABQMAAADBAAACgIAAAKA' +
    'AAACgAAABQNAAANAwAADQMAAA0AABQOAAAOAwAADgMAAA4AABQPAAAPBAAADwQAABAAAAAQ' +
    'AgAAAAECAAAFAQAAAAUAABQBAAABAQAAAQEAABQCAAACAgAAAgIAABQDAAADAgAAAwIAAAQC' +
    'AAAEAgAABAIAABQFAAAFAQAAAAUAABQGAAAGAgAABgIAABQHAAAHAgAABwIAABQIAAAIAgAA' +
    'CAIAABQJAAAJAgAACQIAABQJAAAKAQAACgEAABQMAAADBAAACgIAAAKAABQNAAANAwAADQMA' +
    'ABQOAAAOAwAADgMAABQPAAAPBAAADwQAACgAAwAEAAgADAAQAFAAWABwAIgAmACoALgA0ADg' +
    'APAA+AEIAagBwAHoAfACGAIoAmACeAKYAqgCwALgAvgDGAMwA0ADYAOAABAAMAEgACQATACY' +
    'ANwBEAFIAYgBuAHoAfgCCAJAAmACiAKgAtADAAMoA1ADgAAUAAAADAAUACwAQAAsAEQAUABE'
    ).slice(180);